/*---------------------------------------------------------
  The options statement below should be placed
  before the data step when submitting this code.
---------------------------------------------------------*/
options VALIDMEMNAME=EXTEND VALIDVARNAME=ANY;
   /*------------------------------------------
   Generated SAS Scoring Code
     Date             : 30May2024:05:06:13
     Locale           : en_US
     Model Type       : Decision Tree
     Interval variable: Price per Unit
     Interval variable: Total Sales
     Interval variable: Units Sold
     Class variable   : Product
     Class variable   : Retailer
     Class variable   : State
     Response variable: Product
     ------------------------------------------*/
   /*---------------------------------------------------------
   SAS Code Generated by Cloud Analytic Services for Decision Tree
     Date                  : 30May2024:09:06:13 UTC
     Number of Nodes       : 49
     Number of Tree Depth  : 6
     Number of Bins        : 50
     Number of Obs         : 9360
     -------------------------------------------------------*/

   length _strfmt_ $14; drop _strfmt_;
   _strfmt_ = ' ';

   array _tlevname_2956_{6} $25 _temporary_ ( 'Men''s Apparel' 
   'Men''s Athletic Footwear' 
   'Men''s Street Footwear' 
   'Women''s Apparel' 
   'Women''s Athletic Footwear' 
   'Women''s Street Footwear');

   array _dt_fi_2956_{6} _temporary_;

   _node_id_ =  0;
   _new_id_  = -1;
   nextnode_2956:
   if _node_id_ eq 0 then do;
         _numval_ = 'Units Sold'n;
         if missing(_numval_) then do;
            _numval_ = -1.7976931348623E308;
         end;
         if (_numval_ ge 11 and _numval_ lt 128) then do;

            _new_id_ = 1;
         end;
         else if (_numval_ ge 0 and _numval_ lt 11) then do;

            _new_id_ = 2;
         end;
         else if (_numval_ lt 0) then do;
            _new_id_ = 2;
         end;
         else if (_numval_ ge 128) then do;
            _new_id_ = 1;
         end;
         else do;
         _new_id_ = 1;
         end;
   end;
   else if _node_id_ eq 1 then do;
         _numval_ = 'Price per Unit'n;
         if missing(_numval_) then do;
            _numval_ = -1.7976931348623E308;
         end;
         if (_numval_ ge 55 and _numval_ lt 110) then do;

            _new_id_ = 3;
         end;
         else if (_numval_ ge 7 and _numval_ lt 55) then do;

            _new_id_ = 4;
         end;
         else if (_numval_ lt 7) then do;
            _new_id_ = 4;
         end;
         else if (_numval_ ge 110) then do;
            _new_id_ = 3;
         end;
         else do;
         _new_id_ = 4;
         end;
   end;
   else if _node_id_ eq 2 then do;
         _numval_ = 'Price per Unit'n;
         if missing(_numval_) then do;
            _numval_ = -1.7976931348623E308;
         end;
         if (_numval_ ge 46 and _numval_ lt 110) then do;

            _new_id_ = 5;
         end;
         else if (_numval_ ge 7 and _numval_ lt 46) then do;

            _new_id_ = 6;
         end;
         else if (_numval_ lt 7) then do;
            _new_id_ = 6;
         end;
         else if (_numval_ ge 110) then do;
            _new_id_ = 5;
         end;
         else do;
         _new_id_ = 6;
         end;
   end;
   else if _node_id_ eq 3 then do;
         _strfmt_ = left(trim(put(State,$14.)));
         if _strfmt_ in ('New York',
         'New Mexico',
         'Ohio',
         'Idaho',
         'Arkansas',
         'Louisiana',
         'Vermont',
         'Oregon',
         'Maine',
         'Massachusetts',
         'South Carolina',
         'Pennsylvania',
         'Colorado',
         'Florida',
         'California',
         'Mississippi',
         'Washington',
         'Nevada',
         'Alabama',
         'Georgia',
         'Virginia',
         'Connecticut',
         'Delaware',
         'Arizona',
         'North Carolina',
         'Texas',
         'New Hampshire') then do;

         _new_id_ = 7;
         end;
         else if _strfmt_ in ('Kentucky',
         'Oklahoma',
         'Iowa',
         'Tennessee',
         'Maryland',
         'Indiana',
         'Montana',
         'Kansas',
         'Minnesota',
         'New Jersey',
         'West Virginia',
         'Illinois',
         'Nebraska',
         'Michigan',
         'South Dakota',
         'Wisconsin',
         'North Dakota',
         'Wyoming',
         'Rhode Island') then do;

         _new_id_ = 8;
         end;
         else do;
         _new_id_ = 7;
         end;
   end;
   else if _node_id_ eq 4 then do;
         _numval_ = 'Price per Unit'n;
         if missing(_numval_) then do;
            _numval_ = -1.7976931348623E308;
         end;
         if (_numval_ ge 35 and _numval_ lt 110) then do;

            _new_id_ = 9;
         end;
         else if (_numval_ ge 7 and _numval_ lt 35) then do;

            _new_id_ = 10;
         end;
         else if (_numval_ lt 7) then do;
            _new_id_ = 10;
         end;
         else if (_numval_ ge 110) then do;
            _new_id_ = 9;
         end;
         else do;
         _new_id_ = 9;
         end;
   end;
   else if _node_id_ eq 5 then do;
         _numval_ = 'Units Sold'n;
         if missing(_numval_) then do;
            _numval_ = -1.7976931348623E308;
         end;
         if (_numval_ ge 6 and _numval_ lt 128) then do;

            _new_id_ = 11;
         end;
         else if (_numval_ ge 0 and _numval_ lt 6) then do;

            _new_id_ = 12;
         end;
         else if (_numval_ lt 0) then do;
            _new_id_ = 12;
         end;
         else if (_numval_ ge 128) then do;
            _new_id_ = 11;
         end;
         else do;
         _new_id_ = 11;
         end;
   end;
   else if _node_id_ eq 6 then do;
         _numval_ = 'Units Sold'n;
         if missing(_numval_) then do;
            _numval_ = -1.7976931348623E308;
         end;
         if (_numval_ ge 4 and _numval_ lt 128) then do;

            _new_id_ = 13;
         end;
         else if (_numval_ ge 0 and _numval_ lt 4) then do;

            _new_id_ = 14;
         end;
         else if (_numval_ lt 0) then do;
            _new_id_ = 14;
         end;
         else if (_numval_ ge 128) then do;
            _new_id_ = 13;
         end;
         else do;
         _new_id_ = 13;
         end;
   end;
   else if _node_id_ eq 7 then do;
         _numval_ = 'Price per Unit'n;
         if missing(_numval_) then do;
            _numval_ = -1.7976931348623E308;
         end;
         if (_numval_ ge 67 and _numval_ lt 110) then do;

            _new_id_ = 15;
         end;
         else if (_numval_ ge 7 and _numval_ lt 67) then do;

            _new_id_ = 16;
         end;
         else if (_numval_ lt 7) then do;
            _new_id_ = 16;
         end;
         else if (_numval_ ge 110) then do;
            _new_id_ = 15;
         end;
         else do;
         _new_id_ = 16;
         end;
   end;
   else if _node_id_ eq 8 then do;
         _numval_ = 'Units Sold'n;
         if missing(_numval_) then do;
            _numval_ = -1.7976931348623E308;
         end;
         if (_numval_ ge 60 and _numval_ lt 128) then do;

            _new_id_ = 17;
         end;
         else if (_numval_ ge 0 and _numval_ lt 60) then do;

            _new_id_ = 18;
         end;
         else if (_numval_ lt 0) then do;
            _new_id_ = 18;
         end;
         else if (_numval_ ge 128) then do;
            _new_id_ = 17;
         end;
         else do;
         _new_id_ = 18;
         end;
   end;
   else if _node_id_ eq 9 then do;
         _numval_ = 'Units Sold'n;
         if missing(_numval_) then do;
            _numval_ = -1.7976931348623E308;
         end;
         if (_numval_ ge 45 and _numval_ lt 128) then do;

            _new_id_ = 19;
         end;
         else if (_numval_ ge 0 and _numval_ lt 45) then do;

            _new_id_ = 20;
         end;
         else if (_numval_ lt 0) then do;
            _new_id_ = 20;
         end;
         else if (_numval_ ge 128) then do;
            _new_id_ = 19;
         end;
         else do;
         _new_id_ = 20;
         end;
   end;
   else if _node_id_ eq 10 then do;
         _strfmt_ = left(trim(put(State,$14.)));
         if _strfmt_ in ('Kentucky',
         'New York',
         'Oklahoma',
         'Missouri',
         'Iowa',
         'Ohio',
         'Tennessee',
         'Idaho',
         'Arkansas',
         'Louisiana',
         'Indiana',
         'Kansas',
         'South Carolina',
         'West Virginia',
         'Nebraska',
         'California',
         'Mississippi',
         'Michigan',
         'Alabama',
         'Utah',
         'Wisconsin',
         'Georgia',
         'Virginia',
         'Arizona',
         'North Carolina',
         'Texas',
         'North Dakota') then do;

         _new_id_ = 21;
         end;
         else if _strfmt_ in ('New Mexico',
         'Vermont',
         'Maryland',
         'Oregon',
         'Maine',
         'Massachusetts',
         'Montana',
         'Minnesota',
         'New Jersey',
         'Pennsylvania',
         'Illinois',
         'Colorado',
         'Florida',
         'South Dakota',
         'Washington',
         'Nevada',
         'Connecticut',
         'Delaware',
         'Wyoming',
         'New Hampshire',
         'Rhode Island') then do;

         _new_id_ = 22;
         end;
         else do;
         _new_id_ = 21;
         end;
   end;
   else if _node_id_ eq 11 then do;
         _numval_ = 'Price per Unit'n;
         if missing(_numval_) then do;
            _numval_ = -1.7976931348623E308;
         end;
         if (_numval_ ge 60 and _numval_ lt 110) then do;

            _new_id_ = 23;
         end;
         else if (_numval_ ge 7 and _numval_ lt 60) then do;

            _new_id_ = 24;
         end;
         else if (_numval_ lt 7) then do;
            _new_id_ = 24;
         end;
         else if (_numval_ ge 110) then do;
            _new_id_ = 23;
         end;
         else do;
         _new_id_ = 24;
         end;
   end;
   else if _node_id_ eq 12 then do;
         _leaf_id_ = 12;
         _new_id_ = -1;
         _dt_pred_lev_ = 0;
         _dt_pred_prob_ =              0.71875;
         _dt_fi_2956_{1} =              0.71875; 
         _dt_fi_2956_{2} =              0.03125; 
         _dt_fi_2956_{3} =                    0; 
         _dt_fi_2956_{4} =              0.03125; 
         _dt_fi_2956_{5} =             0.140625; 
         _dt_fi_2956_{6} =             0.078125; 
   end;
   else if _node_id_ eq 13 then do;
         _strfmt_ = left(trim(put(State,$14.)));
         if _strfmt_ in ('Kentucky',
         'Oklahoma',
         'Missouri',
         'Iowa',
         'Arkansas',
         'Vermont',
         'Maryland',
         'Oregon',
         'Indiana',
         'Maine',
         'Massachusetts',
         'Kansas',
         'Minnesota',
         'New Jersey',
         'Pennsylvania',
         'West Virginia',
         'Nebraska',
         'South Dakota',
         'Utah',
         'Wisconsin',
         'Connecticut',
         'Delaware',
         'North Dakota',
         'New Hampshire',
         'Rhode Island') then do;

         _new_id_ = 25;
         end;
         else if _strfmt_ in ('New Mexico',
         'Ohio',
         'Tennessee',
         'Idaho',
         'Louisiana',
         'Montana',
         'Illinois',
         'Colorado',
         'Florida',
         'California',
         'Mississippi',
         'Michigan',
         'Nevada',
         'Alabama',
         'Georgia',
         'Virginia',
         'Arizona',
         'Texas',
         'Wyoming') then do;

         _new_id_ = 26;
         end;
         else do;
         _new_id_ = 25;
         end;
   end;
   else if _node_id_ eq 14 then do;
         _numval_ = 'Price per Unit'n;
         if missing(_numval_) then do;
            _numval_ = -1.7976931348623E308;
         end;
         if (_numval_ ge 40 and _numval_ lt 110) then do;

            _new_id_ = 27;
         end;
         else if (_numval_ ge 7 and _numval_ lt 40) then do;

            _new_id_ = 28;
         end;
         else if (_numval_ lt 7) then do;
            _new_id_ = 28;
         end;
         else if (_numval_ ge 110) then do;
            _new_id_ = 27;
         end;
         else do;
         _new_id_ = 28;
         end;
   end;
   else if _node_id_ eq 15 then do;
         _leaf_id_ = 15;
         _new_id_ = -1;
         _dt_pred_lev_ = 3;
         _dt_pred_prob_ =     0.42533081285444;
         _dt_fi_2956_{1} =     0.20037807183364; 
         _dt_fi_2956_{2} =     0.09262759924385; 
         _dt_fi_2956_{3} =     0.10586011342155; 
         _dt_fi_2956_{4} =     0.42533081285444; 
         _dt_fi_2956_{5} =     0.08317580340264; 
         _dt_fi_2956_{6} =     0.09262759924385; 
   end;
   else if _node_id_ eq 16 then do;
         _numval_ = 'Units Sold'n;
         if missing(_numval_) then do;
            _numval_ = -1.7976931348623E308;
         end;
         if (_numval_ ge 53 and _numval_ lt 128) then do;

            _new_id_ = 29;
         end;
         else if (_numval_ ge 0 and _numval_ lt 53) then do;

            _new_id_ = 30;
         end;
         else if (_numval_ lt 0) then do;
            _new_id_ = 30;
         end;
         else if (_numval_ ge 128) then do;
            _new_id_ = 29;
         end;
         else do;
         _new_id_ = 30;
         end;
   end;
   else if _node_id_ eq 17 then do;
         _strfmt_ = left(trim(put(State,$14.)));
         if _strfmt_ in ('Tennessee',
         'Montana',
         'Michigan',
         'Wyoming') then do;

         _new_id_ = 31;
         end;
         else if _strfmt_ in ('Oklahoma',
         'Indiana',
         'Kansas',
         'West Virginia') then do;

         _new_id_ = 32;
         end;
         else do;
         _new_id_ = 31;
         end;
   end;
   else if _node_id_ eq 18 then do;
         _leaf_id_ = 18;
         _new_id_ = -1;
         _dt_pred_lev_ = 3;
         _dt_pred_prob_ =     0.48375451263537;
         _dt_fi_2956_{1} =     0.23465703971119; 
         _dt_fi_2956_{2} =     0.03610108303249; 
         _dt_fi_2956_{3} =      0.1985559566787; 
         _dt_fi_2956_{4} =     0.48375451263537; 
         _dt_fi_2956_{5} =     0.03249097472924; 
         _dt_fi_2956_{6} =     0.01444043321299; 
   end;
   else if _node_id_ eq 19 then do;
         _strfmt_ = left(trim(put(State,$14.)));
         if _strfmt_ in ('New York',
         'Ohio',
         'Tennessee',
         'Idaho',
         'Montana',
         'South Carolina',
         'Florida',
         'California',
         'Michigan',
         'Alabama',
         'North Carolina',
         'Texas',
         'Wyoming') then do;

         _new_id_ = 33;
         end;
         else if _strfmt_ in ('Kentucky',
         'Oklahoma',
         'Missouri',
         'New Mexico',
         'Iowa',
         'Arkansas',
         'Louisiana',
         'Vermont',
         'Maryland',
         'Oregon',
         'Indiana',
         'Maine',
         'Massachusetts',
         'Kansas',
         'Minnesota',
         'New Jersey',
         'Pennsylvania',
         'West Virginia',
         'Illinois',
         'Colorado',
         'Nebraska',
         'Mississippi',
         'South Dakota',
         'Washington',
         'Nevada',
         'Utah',
         'Wisconsin',
         'Georgia',
         'Virginia',
         'Connecticut',
         'Delaware',
         'Arizona',
         'North Dakota',
         'New Hampshire',
         'Rhode Island') then do;

         _new_id_ = 34;
         end;
         else do;
         _new_id_ = 33;
         end;
   end;
   else if _node_id_ eq 20 then do;
         _numval_ = 'Total Sales'n;
         if missing(_numval_) then do;
            _numval_ = -1.7976931348623E308;
         end;
         if (_numval_ ge 188 and _numval_ lt 8250) then do;

            _new_id_ = 35;
         end;
         else if (_numval_ ge 0 and _numval_ lt 188) then do;

            _new_id_ = 36;
         end;
         else if (_numval_ lt 0) then do;
            _new_id_ = 36;
         end;
         else if (_numval_ ge 8250) then do;
            _new_id_ = 35;
         end;
         else do;
         _new_id_ = 36;
         end;
   end;
   else if _node_id_ eq 21 then do;
         _numval_ = 'Units Sold'n;
         if missing(_numval_) then do;
            _numval_ = -1.7976931348623E308;
         end;
         if (_numval_ ge 15 and _numval_ lt 128) then do;

            _new_id_ = 37;
         end;
         else if (_numval_ ge 0 and _numval_ lt 15) then do;

            _new_id_ = 38;
         end;
         else if (_numval_ lt 0) then do;
            _new_id_ = 38;
         end;
         else if (_numval_ ge 128) then do;
            _new_id_ = 37;
         end;
         else do;
         _new_id_ = 37;
         end;
   end;
   else if _node_id_ eq 22 then do;
         _numval_ = 'Total Sales'n;
         if missing(_numval_) then do;
            _numval_ = -1.7976931348623E308;
         end;
         if (_numval_ ge 67 and _numval_ lt 8250) then do;

            _new_id_ = 39;
         end;
         else if (_numval_ ge 0 and _numval_ lt 67) then do;

            _new_id_ = 40;
         end;
         else if (_numval_ lt 0) then do;
            _new_id_ = 40;
         end;
         else if (_numval_ ge 8250) then do;
            _new_id_ = 39;
         end;
         else do;
         _new_id_ = 40;
         end;
   end;
   else if _node_id_ eq 23 then do;
         _numval_ = 'Total Sales'n;
         if missing(_numval_) then do;
            _numval_ = -1.7976931348623E308;
         end;
         if (_numval_ ge 77 and _numval_ lt 8250) then do;

            _new_id_ = 41;
         end;
         else if (_numval_ ge 0 and _numval_ lt 77) then do;

            _new_id_ = 42;
         end;
         else if (_numval_ lt 0) then do;
            _new_id_ = 42;
         end;
         else if (_numval_ ge 8250) then do;
            _new_id_ = 41;
         end;
         else do;
         _new_id_ = 42;
         end;
   end;
   else if _node_id_ eq 24 then do;
         _numval_ = 'Total Sales'n;
         if missing(_numval_) then do;
            _numval_ = -1.7976931348623E308;
         end;
         if (_numval_ ge 38 and _numval_ lt 8250) then do;

            _new_id_ = 43;
         end;
         else if (_numval_ ge 0 and _numval_ lt 38) then do;

            _new_id_ = 44;
         end;
         else if (_numval_ lt 0) then do;
            _new_id_ = 44;
         end;
         else if (_numval_ ge 8250) then do;
            _new_id_ = 43;
         end;
         else do;
         _new_id_ = 43;
         end;
   end;
   else if _node_id_ eq 25 then do;
         _numval_ = 'Total Sales'n;
         if missing(_numval_) then do;
            _numval_ = -1.7976931348623E308;
         end;
         if (_numval_ ge 47 and _numval_ lt 8250) then do;

            _new_id_ = 45;
         end;
         else if (_numval_ ge 0 and _numval_ lt 47) then do;

            _new_id_ = 46;
         end;
         else if (_numval_ lt 0) then do;
            _new_id_ = 46;
         end;
         else if (_numval_ ge 8250) then do;
            _new_id_ = 45;
         end;
         else do;
         _new_id_ = 46;
         end;
   end;
   else if _node_id_ eq 26 then do;
         _strfmt_ = left(trim(put(Retailer,$13.)));
         if _strfmt_ in ('West Gear',
         'Sports Direct',
         'Kohl''s') then do;

         _new_id_ = 47;
         end;
         else if _strfmt_ in ('Walmart',
         'Amazon',
         'Foot Locker') then do;

         _new_id_ = 48;
         end;
         else do;
         _new_id_ = 48;
         end;
   end;
   else if _node_id_ eq 27 then do;
         _leaf_id_ = 27;
         _new_id_ = -1;
         _dt_pred_lev_ = 0;
         _dt_pred_prob_ =     0.66666666666666;
         _dt_fi_2956_{1} =     0.66666666666666; 
         _dt_fi_2956_{2} =                    0; 
         _dt_fi_2956_{3} =                    0; 
         _dt_fi_2956_{4} =                    0; 
         _dt_fi_2956_{5} =     0.27777777777777; 
         _dt_fi_2956_{6} =     0.05555555555555; 
   end;
   else if _node_id_ eq 28 then do;
         _leaf_id_ = 28;
         _new_id_ = -1;
         _dt_pred_lev_ = 4;
         _dt_pred_prob_ =     0.78070175438596;
         _dt_fi_2956_{1} =     0.08771929824561; 
         _dt_fi_2956_{2} =     0.05263157894736; 
         _dt_fi_2956_{3} =                    0; 
         _dt_fi_2956_{4} =                    0; 
         _dt_fi_2956_{5} =     0.78070175438596; 
         _dt_fi_2956_{6} =     0.07894736842105; 
   end;
   else if _node_id_ eq 29 then do;
         _leaf_id_ = 29;
         _new_id_ = -1;
         _dt_pred_lev_ = 2;
         _dt_pred_prob_ =     0.31155778894472;
         _dt_fi_2956_{1} =     0.14824120603015; 
         _dt_fi_2956_{2} =     0.21356783919597; 
         _dt_fi_2956_{3} =     0.31155778894472; 
         _dt_fi_2956_{4} =     0.14070351758793; 
         _dt_fi_2956_{5} =     0.06783919597989; 
         _dt_fi_2956_{6} =      0.1180904522613; 
   end;
   else if _node_id_ eq 30 then do;
         _leaf_id_ = 30;
         _new_id_ = -1;
         _dt_pred_lev_ = 0;
         _dt_pred_prob_ =     0.23165137614678;
         _dt_fi_2956_{1} =     0.23165137614678; 
         _dt_fi_2956_{2} =     0.15137614678899; 
         _dt_fi_2956_{3} =     0.14105504587155; 
         _dt_fi_2956_{4} =     0.18348623853211; 
         _dt_fi_2956_{5} =     0.14334862385321; 
         _dt_fi_2956_{6} =     0.14908256880733; 
   end;
   else if _node_id_ eq 31 then do;
         _leaf_id_ = 31;
         _new_id_ = -1;
         _dt_pred_lev_ = 3;
         _dt_pred_prob_ =                  0.5;
         _dt_fi_2956_{1} =                    0; 
         _dt_fi_2956_{2} =              0.15625; 
         _dt_fi_2956_{3} =                 0.25; 
         _dt_fi_2956_{4} =                  0.5; 
         _dt_fi_2956_{5} =                    0; 
         _dt_fi_2956_{6} =              0.09375; 
   end;
   else if _node_id_ eq 32 then do;
         _leaf_id_ = 32;
         _new_id_ = -1;
         _dt_pred_lev_ = 2;
         _dt_pred_prob_ =                    1;
         _dt_fi_2956_{1} =                    0; 
         _dt_fi_2956_{2} =                    0; 
         _dt_fi_2956_{3} =                    1; 
         _dt_fi_2956_{4} =                    0; 
         _dt_fi_2956_{5} =                    0; 
         _dt_fi_2956_{6} =                    0; 
   end;
   else if _node_id_ eq 33 then do;
         _leaf_id_ = 33;
         _new_id_ = -1;
         _dt_pred_lev_ = 5;
         _dt_pred_prob_ =     0.19769673704414;
         _dt_fi_2956_{1} =     0.09980806142034; 
         _dt_fi_2956_{2} =      0.1957773512476; 
         _dt_fi_2956_{3} =     0.18809980806142; 
         _dt_fi_2956_{4} =     0.12859884836852; 
         _dt_fi_2956_{5} =     0.19001919385796; 
         _dt_fi_2956_{6} =     0.19769673704414; 
   end;
   else if _node_id_ eq 34 then do;
         _leaf_id_ = 34;
         _new_id_ = -1;
         _dt_pred_lev_ = 2;
         _dt_pred_prob_ =     0.68320610687022;
         _dt_fi_2956_{1} =     0.01145038167938; 
         _dt_fi_2956_{2} =     0.12595419847328; 
         _dt_fi_2956_{3} =     0.68320610687022; 
         _dt_fi_2956_{4} =     0.08015267175572; 
         _dt_fi_2956_{5} =     0.03435114503816; 
         _dt_fi_2956_{6} =      0.0648854961832; 
   end;
   else if _node_id_ eq 35 then do;
         _leaf_id_ = 35;
         _new_id_ = -1;
         _dt_pred_lev_ = 4;
         _dt_pred_prob_ =      0.2243654822335;
         _dt_fi_2956_{1} =     0.21218274111675; 
         _dt_fi_2956_{2} =     0.21624365482233; 
         _dt_fi_2956_{3} =     0.03857868020304; 
         _dt_fi_2956_{4} =     0.12588832487309; 
         _dt_fi_2956_{5} =      0.2243654822335; 
         _dt_fi_2956_{6} =     0.18274111675126; 
   end;
   else if _node_id_ eq 36 then do;
         _leaf_id_ = 36;
         _new_id_ = -1;
         _dt_pred_lev_ = 2;
         _dt_pred_prob_ =      0.2555187637969;
         _dt_fi_2956_{1} =     0.12417218543046; 
         _dt_fi_2956_{2} =     0.18929359823399; 
         _dt_fi_2956_{3} =      0.2555187637969; 
         _dt_fi_2956_{4} =     0.14293598233995; 
         _dt_fi_2956_{5} =      0.1274834437086; 
         _dt_fi_2956_{6} =     0.16059602649006; 
   end;
   else if _node_id_ eq 37 then do;
         _leaf_id_ = 37;
         _new_id_ = -1;
         _dt_pred_lev_ = 2;
         _dt_pred_prob_ =     0.30257510729613;
         _dt_fi_2956_{1} =     0.02575107296137; 
         _dt_fi_2956_{2} =     0.19527896995708; 
         _dt_fi_2956_{3} =     0.30257510729613; 
         _dt_fi_2956_{4} =     0.11695278969957; 
         _dt_fi_2956_{5} =      0.1362660944206; 
         _dt_fi_2956_{6} =     0.22317596566523; 
   end;
   else if _node_id_ eq 38 then do;
         _leaf_id_ = 38;
         _new_id_ = -1;
         _dt_pred_lev_ = 5;
         _dt_pred_prob_ =     0.23372781065088;
         _dt_fi_2956_{1} =     0.10059171597633; 
         _dt_fi_2956_{2} =     0.14497041420118; 
         _dt_fi_2956_{3} =     0.11834319526627; 
         _dt_fi_2956_{4} =     0.18343195266272; 
         _dt_fi_2956_{5} =      0.2189349112426; 
         _dt_fi_2956_{6} =     0.23372781065088; 
   end;
   else if _node_id_ eq 39 then do;
         _leaf_id_ = 39;
         _new_id_ = -1;
         _dt_pred_lev_ = 5;
         _dt_pred_prob_ =     0.74074074074074;
         _dt_fi_2956_{1} =                    0; 
         _dt_fi_2956_{2} =     0.03703703703703; 
         _dt_fi_2956_{3} =     0.16666666666666; 
         _dt_fi_2956_{4} =                    0; 
         _dt_fi_2956_{5} =     0.05555555555555; 
         _dt_fi_2956_{6} =     0.74074074074074; 
   end;
   else if _node_id_ eq 40 then do;
         _leaf_id_ = 40;
         _new_id_ = -1;
         _dt_pred_lev_ = 2;
         _dt_pred_prob_ =                 0.56;
         _dt_fi_2956_{1} =                    0; 
         _dt_fi_2956_{2} =                 0.12; 
         _dt_fi_2956_{3} =                 0.56; 
         _dt_fi_2956_{4} =                 0.04; 
         _dt_fi_2956_{5} =                 0.07; 
         _dt_fi_2956_{6} =                 0.21; 
   end;
   else if _node_id_ eq 41 then do;
         _leaf_id_ = 41;
         _new_id_ = -1;
         _dt_pred_lev_ = 0;
         _dt_pred_prob_ =                    1;
         _dt_fi_2956_{1} =                    1; 
         _dt_fi_2956_{2} =                    0; 
         _dt_fi_2956_{3} =                    0; 
         _dt_fi_2956_{4} =                    0; 
         _dt_fi_2956_{5} =                    0; 
         _dt_fi_2956_{6} =                    0; 
   end;
   else if _node_id_ eq 42 then do;
         _leaf_id_ = 42;
         _new_id_ = -1;
         _dt_pred_lev_ = 3;
         _dt_pred_prob_ =     0.58823529411764;
         _dt_fi_2956_{1} =     0.30392156862745; 
         _dt_fi_2956_{2} =     0.05882352941176; 
         _dt_fi_2956_{3} =     0.00980392156862; 
         _dt_fi_2956_{4} =     0.58823529411764; 
         _dt_fi_2956_{5} =     0.02941176470588; 
         _dt_fi_2956_{6} =     0.00980392156862; 
   end;
   else if _node_id_ eq 43 then do;
         _leaf_id_ = 43;
         _new_id_ = -1;
         _dt_pred_lev_ = 3;
         _dt_pred_prob_ =     0.31118881118881;
         _dt_fi_2956_{1} =     0.19230769230769; 
         _dt_fi_2956_{2} =     0.15734265734265; 
         _dt_fi_2956_{3} =     0.02797202797202; 
         _dt_fi_2956_{4} =     0.31118881118881; 
         _dt_fi_2956_{5} =     0.18881118881118; 
         _dt_fi_2956_{6} =     0.12237762237762; 
   end;
   else if _node_id_ eq 44 then do;
         _leaf_id_ = 44;
         _new_id_ = -1;
         _dt_pred_lev_ = 0;
         _dt_pred_prob_ =      0.4313725490196;
         _dt_fi_2956_{1} =      0.4313725490196; 
         _dt_fi_2956_{2} =     0.16993464052287; 
         _dt_fi_2956_{3} =                    0; 
         _dt_fi_2956_{4} =     0.15032679738562; 
         _dt_fi_2956_{5} =     0.13725490196078; 
         _dt_fi_2956_{6} =     0.11111111111111; 
   end;
   else if _node_id_ eq 45 then do;
         _leaf_id_ = 45;
         _new_id_ = -1;
         _dt_pred_lev_ = 4;
         _dt_pred_prob_ =     0.70491803278688;
         _dt_fi_2956_{1} =      0.1311475409836; 
         _dt_fi_2956_{2} =     0.04918032786885; 
         _dt_fi_2956_{3} =                    0; 
         _dt_fi_2956_{4} =                    0; 
         _dt_fi_2956_{5} =     0.70491803278688; 
         _dt_fi_2956_{6} =     0.11475409836065; 
   end;
   else if _node_id_ eq 46 then do;
         _leaf_id_ = 46;
         _new_id_ = -1;
         _dt_pred_lev_ = 5;
         _dt_pred_prob_ =     0.26556420233463;
         _dt_fi_2956_{1} =     0.14105058365758; 
         _dt_fi_2956_{2} =     0.22178988326848; 
         _dt_fi_2956_{3} =     0.00778210116731; 
         _dt_fi_2956_{4} =     0.12548638132295; 
         _dt_fi_2956_{5} =     0.23832684824902; 
         _dt_fi_2956_{6} =     0.26556420233463; 
   end;
   else if _node_id_ eq 47 then do;
         _leaf_id_ = 47;
         _new_id_ = -1;
         _dt_pred_lev_ = 0;
         _dt_pred_prob_ =     0.53781512605042;
         _dt_fi_2956_{1} =     0.53781512605042; 
         _dt_fi_2956_{2} =     0.00840336134453; 
         _dt_fi_2956_{3} =                    0; 
         _dt_fi_2956_{4} =     0.05042016806722; 
         _dt_fi_2956_{5} =     0.36974789915966; 
         _dt_fi_2956_{6} =     0.03361344537815; 
   end;
   else if _node_id_ eq 48 then do;
         _leaf_id_ = 48;
         _new_id_ = -1;
         _dt_pred_lev_ = 4;
         _dt_pred_prob_ =     0.35555555555555;
         _dt_fi_2956_{1} =      0.2074074074074; 
         _dt_fi_2956_{2} =     0.16296296296296; 
         _dt_fi_2956_{3} =     0.01481481481481; 
         _dt_fi_2956_{4} =     0.07407407407407; 
         _dt_fi_2956_{5} =     0.35555555555555; 
         _dt_fi_2956_{6} =     0.18518518518518; 
   end;
   if _new_id_ >= 0 then do;
       _node_id_ = _new_id_;
      goto nextnode_2956;
   end;

   I_Product = _tlevname_2956_{_dt_pred_lev_+1};
   label I_Product = 'Into: Product';
   _i_ = 1;
   _dt_predp_ = _dt_fi_2956_{_i_};
   P_ProductMen_s_Apparel = _dt_predp_;
   label P_ProductMen_s_Apparel = 'Predicted: Product=Men''s Apparel';
   _i_+1;
   _dt_predp_ = _dt_fi_2956_{_i_};
   P_ProductMen_s_Athletic_Footwear = _dt_predp_;
   label P_ProductMen_s_Athletic_Footwear = 'Predicted: Product=Men''s Athletic Footwear';
   _i_+1;
   _dt_predp_ = _dt_fi_2956_{_i_};
   P_ProductMen_s_Street_Footwear = _dt_predp_;
   label P_ProductMen_s_Street_Footwear = 'Predicted: Product=Men''s Street Footwear';
   _i_+1;
   _dt_predp_ = _dt_fi_2956_{_i_};
   P_ProductWomen_s_Apparel = _dt_predp_;
   label P_ProductWomen_s_Apparel = 'Predicted: Product=Women''s Apparel';
   _i_+1;
   _dt_predp_ = _dt_fi_2956_{_i_};
   P_ProductWomen_s_Athletic_Footwe = _dt_predp_;
   label P_ProductWomen_s_Athletic_Footwe = 'Predicted: Product=Women''s Athletic Footwear';
   _i_+1;
   _dt_predp_ = _dt_fi_2956_{_i_};
   P_ProductWomen_s_Street_Footwear = _dt_predp_;
   label P_ProductWomen_s_Street_Footwear = 'Predicted: Product=Women''s Street Footwear';
   _i_+1;
   drop _dt_predp_;
   drop _i_;
   drop _dt_pred_lev_;
   drop _dt_pred_prob_;
   drop _numval_;
   drop _node_id_;
   drop _new_id_;
   /*------------------------------------------*/
   /*_VA_DROP*/ drop 'I_Product'n '_leaf_id_'n 'P_ProductMen_s_Apparel'n 'P_ProductMen_s_Athletic_Footwear'n 'P_ProductMen_s_Street_Footwear'n 'P_ProductWomen_s_Apparel'n 'P_ProductWomen_s_Athletic_Footwe'n 'P_ProductWomen_s_Street_Footwear'n;
length 'I_Product_2956_2'n $25;
      'I_Product_2956_2'n='I_Product'n;
'P_ProductMen_s_Apparel_2956_2'n='P_ProductMen_s_Apparel'n;
'P_ProductMen_s_Athletic_2956_2'n='P_ProductMen_s_Athletic_Footwear'n;
'P_ProductMen_s_Street_F_2956_2'n='P_ProductMen_s_Street_Footwear'n;
'P_ProductWomen_s_Appare_2956_2'n='P_ProductWomen_s_Apparel'n;
'P_ProductWomen_s_Athlet_2956_2'n='P_ProductWomen_s_Athletic_Footwe'n;
'P_ProductWomen_s_Street_2956_2'n='P_ProductWomen_s_Street_Footwear'n;
'_leaf_id__2956_2'n='_leaf_id_'n;
   /*------------------------------------------*/